module ApplicationHelper
  def us_states
      [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
      ]
  end

  def florida_counties
    [
      ['Alachua', 'Alachua'],
      ['Baker', 'Baker'],
      ['Bay', 'Bay'],
      ['Bradford', 'Bradford'],
      ['Brevard', 'Brevard'],
      ['Broward', 'Broward'],
      ['Calhoun', 'Calhoun'],
      ['Charlotte', 'Charlotte'],
      ['Citrus', 'Citrus'],
      ['Clay', 'Clay'],
      ['Collier', 'Collier'],
      ['Columbia', 'Columbia'],
      ['DeSoto', 'DeSoto'],
      ['Dixie', 'Dixie'],
      ['Duval', 'Duval'],
      ['Escambia', 'Escambia'],
      ['Flagler', 'Flagler'],
      ['Franklin', 'Franklin'],
      ['Gadsden', 'Gadsden'],
      ['Gilchrist', 'Gilchrist'],
      ['Glades', 'Glades'],
      ['Gulf', 'Gulf'],
      ['Hamilton', 'Hamilton'],
      ['Hardee', 'Hardee'],
      ['Hendry', 'Hendry'],
      ['Hernando', 'Hernando'],
      ['Highlands', 'Highlands'],
      ['Hillsborough', 'Hillsborough'],
      ['Holmes', 'Holmes'],
      ['Indian', 'Indian'],
      ['Jackson', 'Jackson'],
      ['Jefferson', 'Jefferson'],
      ['Lafayette', 'Lafayette'],
      ['Lake', 'Lake'],
      ['Lee', 'Lee'],
      ['Leon', 'Leon'],
      ['Levy', 'Levy'],
      ['Liberty', 'Liberty'],
      ['Madison', 'Madison'],
      ['Manatee', 'Manatee'],
      ['Marion', 'Marion'],
      ['Martin', 'Martin'],
      ['Miam', 'Miam'],
      ['Monroe', 'Monroe'],
      ['Nassau', 'Nassau'],
      ['Okaloosa', 'Okaloosa'],
      ['Okeechobee', 'Okeechobee'],
      ['Orange', 'Orange'],
      ['Osceola', 'Osceola'],
      ['Palm', 'Palm'],
      ['Pasco', 'Pasco'],
      ['Pinellas', 'Pinellas'],
      ['Polk', 'Polk'],
      ['Putnam', 'Putnam'],
      ['Santa', 'Santa'],
      ['Sarasota', 'Sarasota'],
      ['Seminole', 'Seminole'],
      ['St. Johns', 'St. Johns'],
      ['St. Lucie', 'St. Lucie'],
      ['Sumter', 'Sumter'],
      ['Suwannee', 'Suwannee'],
      ['Taylor', 'Taylor'],
      ['Union', 'Union'],
      ['Volusia', 'Volusia'],
      ['Wakulla', 'Wakulla'],
      ['Walton', 'Walton'],
      ['Washington', 'Washington']
    ]
  end
end
